# Generated by Django 3.2 on 2021-04-15 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_alter_sale_sale_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesdata',
            old_name='price',
            new_name='revenue',
        ),
        migrations.RemoveField(
            model_name='salesdata',
            name='sale',
        ),
        migrations.AddField(
            model_name='salesdata',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='sales_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salesdata',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
