# Generated by Django 3.2 on 2021-04-14 07:57

from django.db import migrations

def create_default_country_amd_city(apps, schema_editor):

    country = apps.get_model("user", "Country")
    country_1 = country.objects.create(name="France")

    city = apps.get_model("user", "City")
    city.objects.create(country = country_1, name="PARIS")
    city.objects.create(country = country_1, name="Marseille")
    
class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_city'),
    ]

    operations = [
        migrations.RunPython(create_default_country_amd_city),
    ]
